export const TURN_ON_MAIN_LOADING = 'TURN_ON_MAIN_LOADING';
export const TURN_OFF_MAIN_LOADING = 'TURN_OFF_MAIN_LOADING';

export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE';

export const TOGGLE_DELETE_DIALOG = 'TOGGLE_DELETE_DIALOG';
export const NOTIFICATION_TOGGLE = 'NOTIFICATION_TOGGLE';

export const USER_LOGIN = 'USER_LOGIN';
