export const USER_LOGIN = "USER_LOGIN";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const GET_USER_COMPANIES = "GET_USER_COMPANIES";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
